import type { Metadata } from 'next';
import './globals.css';
import { Poppins } from 'next/font/google';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Lucas Amsellem - Développeur front-end',
  description: 'Generated by create next app',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <div className={`p-10 ${poppins.className} tracking-[0.3px]`}>{children}</div>

        <Script
          type='module'
          src='https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js'
          strategy='afterInteractive'
        />
        <Script
          src='https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js'
          strategy='afterInteractive'
        />
      </body>
    </html>
  );
}
