import type { Metadata } from 'next';
import './globals.css';
import { Poppins } from 'next/font/google';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const momo = Poppins({ subsets: ['latin'], weight: '400' });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <div className={`p-5 ${momo.className} tracking-wide`}>{children}</div>

        <Script
          type='module'
          src='https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js'
          strategy='afterInteractive'
        />
        <Script
          src='https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js'
          strategy='afterInteractive'
        />
      </body>
    </html>
  );
}
